sudo: false

language: elm
elm:
  - elm0.19.0

git:
  depth: false

if: (branch = master) OR (tag =~ ^v)

jobs:
  include:
    - stage: Build 🔨
      script:
      - FORMAT=$(elm-format --validate src/)
      - test "$FORMAT" = "[]" || (echo $FORMAT && exit 1)

    - stage: Build 🔨
      script:
      - elm make src/Main.elm --optimize --output=app.js
      - git tag

deploy:
  provider: releases
  api_key: $GITHUB_ACCESS_TOKEN
  skip_cleanup: true
  draft: true
  file:
    - app.js
  on:
    repo: elm-toulouse/star-wars-quizz
    branch: master
    tags: true
